# Generated by Django 6.0.6 on 2026-10-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0014_alter_mascota_especie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.CharField(max_length=5)),
                ('hora_fin', models.CharField(max_length=5)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
